doctrine:
  dbal:
    types:
      email: App\DBAL\Types\EmailType
      roles: App\DBAL\Types\RolesType
      work_status: App\DBAL\Types\WorkStatusType
      work_member_status: App\DBAL\Types\Work\MemberStatusType

    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your db driver and server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #driver: 'mysql'
    #server_version: '5.7'

    # Only needed for MySQL (ignored otherwise)
    # charset: utf8mb4
    # default_table_options:
    #   collate: utf8mb4_unicode_ci

    # PostgreSQL
    driver: 'pdo_pgsql'
    server_version: '12.1'
    charset: utf8
    default_table_options:
      charset: utf8
      collate: -

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
    # entity_managers:
    #   default:
    #     dql:
    #       string_functions:
    #         JSON_EXTRACT: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonExtract
    #         JSON_SEARCH: Scienta\DoctrineJsonFunctions\Query\AST\Functions\Mysql\JsonSearch
